name: AL
channels:
      - anaconda
      - conda-forge
      - defaults
      - pytorch
dependencies:
    - python==3.6.8
    - pytorch
    - matplotlib
    - tqdm
    - Pillow
    - scikit-image
    - ipython
    - pip:
        - Flask
        - opencv-python==4.1.0.25
        - keras==2.1.3
        - tensorflow==1.5.0
        - scipy==1.1.0
